### ISSUE TITLE
Where to find Pulpissimo tests? 

### ISSUE THREAD

**Issue by aelgogary** [pulp-platform/pulpissimo#105]
Hi, when i run update-tests script, it asks for a password for Gitlab, is there a copy of the repositories pulp-tests and pulp-sw on Github?

**Comment by bluewww** [comment]
@haugoug

**Comment by haugoug** [comment]
This an internal script that we use for non-regression runs, the repositories are not accessible.

**Comment by Toxic-Scofield** [comment]
Hi, "This an internal script that we use for non-regression runs, the repositories are not accessible."  Does that mean we can not use these tests?

**Comment by haugoug** [comment]
Yes we haven't had time yet to open-source these tests, they cannot be used.

**Comment by bluewww** [comment]
We recently added some tests here
https://github.com/pulp-platform/regression_tests
but we don't refer to them yet in the ./update-tests-scripts
