### ISSUE TITLE
How to  Port the pulpino tests to pupissimo ?

### ISSUE THREAD

**Issue by DonQuixote-lab** [pulp-platform/pulpissimo#110]
Now I can run the hello world on my ZCU102 board! But the appication compiled for the FPGA target comes from pulp-rt-examples. If I want to test the pulpissimo on fpga,what should I do?Is there a way to Port the pulpino tests to pupissimo

**Comment by bluewww** [comment]
@haugoug

**Comment by haugoug** [comment]
We just provide pulp-rt-examples. I don't think Pulpino tests can easily be run on Pulpissimo

**Comment by bluewww** [comment]
Most tests are available here https://github.com/pulp-platform/regression_tests
