### ISSUE TITLE
Implement pulpissmo on VCU1525

### ISSUE THREAD

**Issue by AnouarNechi** [pulp-platform/pulpissimo#120]
I am trying to implement Pulpissimo on the [VCU1525 (Virtex Ultrascale+) ](https://www.xilinx.com/products/boards-and-kits/vcu1525-a.html#hardware). But the problem that I have difficulties to map in IO pins in the constraint file. 
These are the available I/O's of the board:

- FPGA Configuration via **JTAG** thru Micro USB Port
- 2x **QSFP28** 100G Interfaces
- **PCIe** Gen3 x 16 or Gen4 x8 via Edge Connector

 
could someone help me regarding this matter?

**Comment by erka123321** [comment]
Hello, can you provide me with the complete source codes？

**Comment by bluewww** [comment]
Please open another issue if this is still relevant
