### ISSUE TITLE
 Accelerator HWPE Example Loops on ZedBoard 

### ISSUE THREAD

**Issue by acastillo18** [pulp-platform/pulpissimo#127]
Right now I am trying to run the accelerator example on the zedboard, but right now I have a issue regarding of running the application. For some reason after this line of code __rt_periph_wait_event(ARCHI_SOC_EVENT_FCHWPE0, 1), the application loops. What can be a good approach to fix it?  
![Screenshot from 2020-04-18 16-03-29](https://user-images.githubusercontent.com/55512740/79639808-3dc6cf80-818e-11ea-84ad-879a3098e98e.png)

**Comment by bluewww** [comment]
You could try to set a breakpoint in `main` and single step

**Comment by acastillo18** [comment]
Hi, I did what you suggest me but still the examples loops.

**Comment by bluewww** [comment]
It is hard to tell what is going wrong in your case. If you don't get enough insight running it on an FPGA you can always use a simulator, but I believe single stepping through the assembly should give some insight.

**Comment by LPLATU** [comment]
Maybe this will help?
https://github.com/pulp-platform/pulpissimo/issues/104

**Comment by bluewww** [comment]
Please open another issue if this is still relevant. `pulp_soc` (https://github.com/pulp-platform/pulp_soc/commit/84aa62fe43df072433ef02c80b61e6cc54c1a95f) has some hwpe updates that will soon propagate into pulpissimo master
