### ISSUE TITLE
How to add ibex/ri5cy into pulpissimo？

### ISSUE THREAD

**Issue by yywang1993** [pulp-platform/pulpissimo#144]
It seems like there is no Core RTL in pulpissimo？How could I add ibex or ri5cy into pulpissimo？
I‘m a new user, is there some userguide about pulpissimo?

**Comment by Marcello996** [comment]
All the files related to ri5cy are downloaded during the "installation" procedure.

**Comment by FrancescoConti** [comment]
Have a look at the readme:
https://github.com/pulp-platform/pulpissimo#getting-started
