### ISSUE TITLE
Support for RISC-V Linux ports.

### ISSUE THREAD

**Issue by 0ena** [pulp-platform/pulpissimo#152]
Hi,

I would like to know if PULPissimo (RI5CY core) is able to run the Linux Kernel or any other port of Linux for RISC-V.

Thank you in advance for your response.

Kind regards,
Nassos

**Comment by bluewww** [comment]
Normally you run linux with virtual memory. We do not have virtual memory support in RI5CY (nowadays called cv32e40p by openhardware) and there are no plans to add it (it does not fit the low power microcontroller profile we are targeting).

You have two possibilities at this point if you insist on running linux:
1. get uclinux (mmu-less linux) port working on RI5CY
2. use Ariane, a 64-bit linux capable RISC-V core
