### ISSUE TITLE
vopt runs without memory

### ISSUE THREAD

**Issue by baraujo3007** [pulp-platform/pulpissimo#154]
Hello, I'm trying to run pulpissimo with modelsim 20.2, but when I do the make build command it got stucked in this line: /home/Bruna/tmp/pulpissimo/sim//tcl_files/rtl_vopt.tcl  

![image](https://user-images.githubusercontent.com/66388932/90802833-335c4400-e2ee-11ea-8561-9143700a32e0.png)

I did a top command in other terminal and it showed that the vopt is running using 30% of CPU but with no memory.

Any ideas why this happenning and how to fix it?

**Comment by bluewww** [comment]
Looks like you are not using questasim, but some other version. This might be the issue.

**Comment by bluewww** [comment]
Please re-open if stil relevant
