### ISSUE TITLE
Pulpissimo FLL

### ISSUE THREAD

**Issue by zyong1234** [pulp-platform/pulpissimo#162]
Hi, we want to do some development based on pulpissimo, but we found that DCO has only one simulation model. Does this mean that we need to buy a complete PLL ip to replace the FLL ip? Is there a cheaper solution? Thanks a lot!

**Comment by bluewww** [comment]
We have a FLL ip for various technologies, but I don't think we can make them available (due to licensing) unfortunately.

**Comment by zyong1234** [comment]
Get it, thank you.

**Comment by FrischAd** [comment]
Of course you can also remove the FLL and use an external clock signal.

**Comment by zyong1234** [comment]
> Of course you can also remove the FLL and use an external clock signal.

Thanks a lot
