### ISSUE TITLE
how to generate a new boot_code.cde

### ISSUE THREAD

**Issue by q3104008073** [pulp-platform/pulpissimo#167]
hi,
these days i try to run makefile to generate boot_code.cde for simulation.
but no matter how i modify the boot_code.c as testing in pulp-sdk/runtime/boot_code_pulpissimo dir
the boot_code.cde generate by "make import_boot_code" keep the same;
what should i do if i want to get the boot_code.cde correcttly!!!
thanks!

**Comment by bluewww** [comment]
I haven't tried this recently, but I guess we can update the documentation when I get around it on how to do this.
