### ISSUE TITLE
JTAG module ( Not Digilent HS1 But Digilent HS2 )

### ISSUE THREAD

**Issue by designer9406** [pulp-platform/pulpissimo#177]
Hi,
I am trying to run pulpissimo with zcu104 board.
But I don't have any JTAG module. So I want to buy Digilent HS2 module.
Is it OK about Digilent HS2 to run PULPissimo?

Thanks.

**Comment by bluewww** [comment]
I never tried this setup so I'm not sure if this works. @marcowidmer did the porting, maybe he can chime in?

**Comment by designer9406** [comment]
Thanks for the reply.
I tried to run PULPissimo with Digilent HS2 JTAG module on the zcu104 board.
And it's working.

Thanks !
