### ISSUE TITLE
Where can i find the definition of __builtin_pulp functions?

### ISSUE THREAD

**Issue by adfad1** [pulp-platform/pulpissimo#179]
hello!
In hwme case and pulp_nn project  I find the use of many __builtin_pulp functions like **#define log2(x) __builtin_pulp_fl1(x)** or **__builtin_pulp_OffsetedWrite**
where can i find the definitions of these functions?

**Comment by bluewww** [comment]
I'm not aware of any documentation we have. You can find the compiler changes here though:
https://github.com/pulp-platform/pulp-riscv-gcc/blob/master/gcc/config/riscv/riscv-builtins.c
https://github.com/pulp-platform/pulp-riscv-gcc/blob/master/gcc/config/riscv/riscv-builtins.c

**Comment by adfad1** [comment]
> I'm not aware of any documentation we have. You can find the compiler changes here though:
> https://github.com/pulp-platform/pulp-riscv-gcc/blob/master/gcc/config/riscv/riscv-builtins.c
> https://github.com/pulp-platform/pulp-riscv-gcc/blob/master/gcc/config/riscv/riscv-builtins.c

Thanks! And I want to use some arithmetic functions in my c code like log(), so i include <math.h>
![image](https://user-images.githubusercontent.com/31584633/96448077-73d03380-1245-11eb-8cd4-3103149b6840.png)

, but it reports error
![image](https://user-images.githubusercontent.com/31584633/96448156-8f3b3e80-1245-11eb-99df-81be7d6cdf42.png)
how can i solve it?
