### ISSUE TITLE
Pulpissimo Software Sources

### ISSUE THREAD

**Issue by msaideroglu** [pulp-platform/pulpissimo#182]
I could not find Pulpissimo sw codes such as .h and .c files just like Pulpino's. Where can I find those files? Because I want to configure uDMA module and I dont know how to do it. 

Also, can uDMA be used as a standart DMA module that is used to communicate with external peripherals as well such as GPIO?

**Comment by bluewww** [comment]
There is the pulp-sdk that contains all the drivers and runtime support https://github.com/pulp-platform/pulp-sdk
