### ISSUE TITLE
Error generating stim.txt file using pulpissimo for hello world example

### ISSUE THREAD

**Issue by tauqeerali-lm** [pulp-platform/pulpissimo#191]
I am trying to generate stim.txt file in hello world example using pulpissimo. When I use make all command, it will generate a error as shown below: 

Is this error is related to toolchain or pulpissimo or gcc compiler?
I am following #123 as a reference to generate stim.txt file.
![Error](https://user-images.githubusercontent.com/73219728/99524896-e9513000-29ba-11eb-8035-58cc5b0627f7.png)

**Comment by bluewww** [comment]
you are using the wrong compiler. It says it right there in the error message
