### ISSUE TITLE
 No such file or directory: 'curl'

### ISSUE THREAD

**Issue by bhyou** [pulp-platform/pulpissimo#194]
hi, could you help me how to solve this problem? When I'm preparing to get the latest version of the IPs composing by running ./update-ips， it is reported as follow: （based on ubuntu16.04.7 LTS ）

Retrieving ips_list.yml dependency list for all IPs (may take some time)...
   Fetching ips_list.yml from https://raw.githubusercontent.com/pulp-platform/pulp_soc/v1.4.1/ips_list.yml
Traceback (most recent call last):
  File "./update-ips", line 44, in <module>
    verbose=args.verbose
  File "ipstools/ipstools/IPDatabase.py", line 132, in __init__
    self.generate_deps_tree(verbose=verbose)
  File "ipstools/ipstools/IPDatabase.py", line 292, in generate_deps_tree
    children.append(IPTreeNode(ip, self.default_server, self.default_group, self.default_commit, verbose=True))
  File "ipstools/ipstools/IPTreeNode.py", line 74, in __init__
    ips = load_ips_list_from_server(server, group, node['name'], commit, verbose=verbose)
  File "ipstools/ipstools/IPApproX_common.py", line 161, in load_ips_list_from_server
    ips_list_yml = get_ips_list_yml(server, group, name, commit, verbose=verbose)
  File "ipstools/ipstools/IPApproX_common.py", line 136, in get_ips_list_yml
    curl = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=devnull)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'curl'

**Comment by bluewww** [comment]
You need to install curl. sudo yum install curl.

**Comment by bhyou** [comment]
all right, thank you very much !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pulp-platform/pulpissimo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月2日(星期三) 晚上8:21
收件人:&nbsp;"pulp-platform/pulpissimo"<pulpissimo@noreply.github.com&gt;;
抄送:&nbsp;"游必辉"<bhyou@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pulp-platform/pulpissimo]  No such file or directory: 'curl' (#194)





 
You need to install curl. sudo yum install curl.
