### ISSUE TITLE
pulpissimo examples: make run needs minicom

### ISSUE THREAD

**Issue by monniaux** [pulp-platform/pulpissimo#211]
The Pulpissimo documentation invites doing `make run` in pulp-rt-examples but it is not said that minicom must be installed.

**Comment by meggiman** [comment]
You are right, that the run target of pulp-sdk when using the FPGA platform requires minicom to observe the UART output. However, this approach of running your application is disgouraged for the FPGA target and thus not documented. Instead, you should follow the README's approach of manually invoking OpenOCD and gdb to gain more control over the program execution. For RTL simulation, however, minicom is not a requirement at all and the "run" target should work without it being installed.
