### ISSUE TITLE
Pulpissimo in Lattice FPGA

### ISSUE THREAD

**Issue by francis2tm** [pulp-platform/pulpissimo#229]
Hello,
I'm writing here to know if you have any resource related to implement pulpissimo SoC in a Lattice FPGA? More specifically, the ECP5

Thanks

**Comment by meggiman** [comment]
Unfortunately, we don't. At least I am not aware of any. So far we've only been focusing on Xilinx FPGAs. PRs are welcome in case you port it yourself ;-)
