### ISSUE TITLE
Confusion with Peripheral Addresses

### ISSUE THREAD

**Issue by vignajeth** [pulp-platform/pulpissimo#234]
Hi
I notice from the datasheet that the advanced time starts from 0x 1A10 5000

![image](https://user-images.githubusercontent.com/22914321/111876108-71613980-899d-11eb-9b08-737f43d98acd.png)

but in the advanced timer register details it starts at  0x 1A10 4000

![image](https://user-images.githubusercontent.com/22914321/111876178-db79de80-899d-11eb-97ee-b93a169a99bc.png)

**Comment by bluewww** [comment]
Thanks for pointing that out. The correct base address is `0x1A10_5000`
