### ISSUE TITLE
Running hello application for ZedBoard FPGA ( no thing displayed with screen /dev/ttyUSB0 115200) 

### ISSUE THREAD

**Issue by mohamedElbouazzati** [pulp-platform/pulpissimo#238]
### Configuration 

- PULP-RISCV-TOOLCHAIN ( Pre-built) 
- PULP-SDK 
- Processor : CV32E40P
- Soc : Pulpissimo 
- Board: ZedBoard FPGA

### JTAG and UART Connections: 

| JTAG Signal | PMOD Pin |
|-------------|----------|
| TMS         | JA1      |
| TDI         | JA2      |
| TDO         | JA3      |
| TCK         | JA4      |
| GND         | JA5      |
| VCC (trgt)  | JA6      |
 
| UART Signal | PMOD Pin |
|-------------|----------|
| RXD         | JA7      |
| TXD         | JA8      |
| GND         | JA11     |

### C Program 

![test](https://user-images.githubusercontent.com/62422381/112665742-a9fc8980-8e5b-11eb-9bc9-df45538fd354.PNG)

### Openocd

![openocd](https://user-images.githubusercontent.com/62422381/112665826-c13b7700-8e5b-11eb-944a-451e8a5cb2e0.PNG)
### GDB 

![gdb](https://user-images.githubusercontent.com/62422381/112666092-12e40180-8e5c-11eb-99c8-2a5d16d5d031.PNG)

### screen /dev/ttyUSB0 115200

![screen](https://user-images.githubusercontent.com/62422381/112666114-1a0b0f80-8e5c-11eb-8912-f35158108bfc.PNG)

I don't know why nothing is displayed on the screen. 
Any suggestions are appreciated 
Thanks!

**Comment by meggiman** [comment]
Hi @mohamedElbouazzati 
Did you try stepping through the printf call using GDB to ensure that the program is actually trying to print to uart? Did you check that there is actually any activity on the UART pins (e.g. with an oscilloscope)?

**Comment by mohamedElbouazzati** [comment]
Hi @meggiman  I tried to do this on a fpga zcu104 and didn't get enough clarity on the uart like this on putty 
![zcu](https://user-images.githubusercontent.com/62422381/116219804-51ffbe00-a74c-11eb-9c2e-175cbee2dd06.PNG)
I have to set the baud rate somewhere in the program, I guess.

**Comment by Ahmed1Zaky** [comment]
Hi @mohamedElbouazzati,

Could you please tell me how did you connect the PMOD to the PC? 

Did you use this lvl shifter board along with the HS2 adapter? https://digilent.com/reference/pmod/pmodlvlshft/reference-manual

or is there any other way to do it? Please advise.

**Comment by Ahmed1Zaky** [comment]
Hi @mohamedElbouazzati , 

Did you end up solving this issue? Did you manage to get the output printed on the Terminal screen?

**Comment by zealshah29** [comment]
Hi @mohamedElbouazzati , @meggiman ,
I am facing the same issue. I also added the breakpoint before continue, yet I can't see any output. If the following issue has been solved, can you help me out with the same?
Also is there any other way to verify if softcore dump was successful on zedboard or not?
I have also created an issue specifying my problem in detail : #409
