### ISSUE TITLE
fpga build fail, files missing

### ISSUE THREAD

**Issue by marrrk** [pulp-platform/pulpissimo#247]
Hi, 
I'm trying to generate bitstreams for supported boards by following the guide on the readme. I However get the following error:

```
couldn't read file "../pulpissimo/tcl/ips_inc_dirs.tcl": no such file or directory
    while executing
"source ../pulpissimo/tcl/ips_inc_dirs.tcl"
    (file "tcl/run.tcl" line 13)
INFO: [Common 17-206] Exiting Vivado at Thu Apr 22 20:22:19 2021...
make[1]: *** [Makefile:11: all] Error 1
```
This is after ensuring `update-ips` has been run.

**Comment by meggiman** [comment]
Hi @marrrk 

Did you run 'make checkout' beforehand? This will call "update-ips" and *'generate-scripts'*. The `generate-scripts` script is necessary to generate the TCL files for simulation in Questasim as well as FPGA synthesis in Vivado. The file you are missing is auto-generated by this script.
