### ISSUE TITLE
Can't use SPI to load the L2

### ISSUE THREAD

**Issue by FrischAd** [pulp-platform/pulpissimo#26]
Hello,

I want to use SPI instead of JTAG to load the L2. I've installed the S25FS256S module and followed the instructions of the vip/spi_flash/README.mk file.
Changing the LOAD_L2 parameter in the testbench has no effect (also USE_S25FS256S_MODEL is set to 1).
The pulp-sdk is using the pulpissimo.sh and the platform-rtl.sh.

Can you reproduce this behaviour?

**Comment by haugoug** [comment]
The platform only supports booting from jtag for now. To boot from SPI, we usually put a ROM with a boot loader with loads the application binary from the SPI flash but this is not yet implemented in pulpissimo.
