### ISSUE TITLE
Pulpissimo new interrupt controller 

### ISSUE THREAD

**Issue by SaraNassef** [pulp-platform/pulpissimo#269]
I was looking into the difference between the PULPino and the PULPissimo interrupt controller and trying to figure out if the new PULPissimo interrupt controller can help decrease the number of clock cycles of the interrupt execution but can’t find enough resources for my research.

**Comment by meggiman** [comment]
This question is not that easy to answer. Why don't you try to just benchmark it on both platforms in simulation?
