### ISSUE TITLE
Coremark results

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulpissimo#27]
I have the following results for coremark on all the core. Why I haven't the same results as you ? 

![image](https://user-images.githubusercontent.com/36438648/42807393-f98567d6-89b0-11e8-83ea-65878d4e554d.png)

Thank you in advance.

**Comment by soyedtuhin** [comment]
@lfernand4 

hey. 
I am trying to run Coremark.
can you tell how did you coreamark?

thank you
