### ISSUE TITLE
There was a problem during make build

### ISSUE THREAD

**Issue by kangliyu1** [pulp-platform/pulpissimo#279]
I have two questions to ask seniors
1. There is a problem during make build, the following is the corresponding log
2.I can’t find the ipstools_cfg.py file under my project. How do I get this file?
log：
cd sim && make all
make[1]: Entering directory '/home/kly/pulpissimo/sim'
mkdir -p /home/kly/pulpissimo/install/modelsim_libs
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap common_cells_lib /home/kly/pulpissimo/install/modelsim_libs/common_cells_lib 
Copying /home/kly/Mentor_Graphics_QuestaSim_10.7c_linux64/Mentor_Graphics_QuestaSim_10.7c_linux64/linux_x86_64/questasim/linux_x86_64/../modelsim.ini to modelsim.ini
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap L2_tcdm_hybrid_interco_lib /home/kly/pulpissimo/install/modelsim_libs/L2_tcdm_hybrid_interco_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap cluster_interconnect_lib /home/kly/pulpissimo/install/modelsim_libs/cluster_interconnect_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap adv_dbg_if_lib /home/kly/pulpissimo/install/modelsim_libs/adv_dbg_if_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb2per_lib /home/kly/pulpissimo/install/modelsim_libs/apb2per_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb_adv_timer_lib /home/kly/pulpissimo/install/modelsim_libs/apb_adv_timer_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb_fll_if_lib /home/kly/pulpissimo/install/modelsim_libs/apb_fll_if_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb_gpio_lib /home/kly/pulpissimo/install/modelsim_libs/apb_gpio_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb_node_lib /home/kly/pulpissimo/install/modelsim_libs/apb_node_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap apb_interrupt_cntrl_lib /home/kly/pulpissimo/install/modelsim_libs/apb_interrupt_cntrl_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap axi_lib /home/kly/pulpissimo/install/modelsim_libs/axi_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap axi_slice_lib /home/kly/pulpissimo/install/modelsim_libs/axi_slice_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap timer_unit_lib /home/kly/pulpissimo/install/modelsim_libs/timer_unit_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap fpu_div_sqrt_mvp_lib /home/kly/pulpissimo/install/modelsim_libs/fpu_div_sqrt_mvp_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap fpnew_lib /home/kly/pulpissimo/install/modelsim_libs/fpnew_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap jtag_pulp_lib /home/kly/pulpissimo/install/modelsim_libs/jtag_pulp_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap cv32e40p_lib /home/kly/pulpissimo/install/modelsim_libs/cv32e40p_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap ibex_lib /home/kly/pulpissimo/install/modelsim_libs/ibex_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap scm_lib /home/kly/pulpissimo/install/modelsim_libs/scm_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap generic_FLL_lib /home/kly/pulpissimo/install/modelsim_libs/generic_FLL_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap tech_cells_generic_lib /home/kly/pulpissimo/install/modelsim_libs/tech_cells_generic_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_core_lib /home/kly/pulpissimo/install/modelsim_libs/udma_core_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_uart_lib /home/kly/pulpissimo/install/modelsim_libs/udma_uart_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_i2c_lib /home/kly/pulpissimo/install/modelsim_libs/udma_i2c_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_i2s_lib /home/kly/pulpissimo/install/modelsim_libs/udma_i2s_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_qspi_lib /home/kly/pulpissimo/install/modelsim_libs/udma_qspi_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_sdio_lib /home/kly/pulpissimo/install/modelsim_libs/udma_sdio_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_camera_lib /home/kly/pulpissimo/install/modelsim_libs/udma_camera_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_filter_lib /home/kly/pulpissimo/install/modelsim_libs/udma_filter_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_external_per_lib /home/kly/pulpissimo/install/modelsim_libs/udma_external_per_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap udma_hyper_lib /home/kly/pulpissimo/install/modelsim_libs/udma_hyper_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap hwpe_ctrl_lib /home/kly/pulpissimo/install/modelsim_libs/hwpe_ctrl_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap hwpe_stream_lib /home/kly/pulpissimo/install/modelsim_libs/hwpe_stream_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap hwpe_mac_engine_lib /home/kly/pulpissimo/install/modelsim_libs/hwpe_mac_engine_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap riscv_dbg_lib /home/kly/pulpissimo/install/modelsim_libs/riscv_dbg_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap register_interface_lib /home/kly/pulpissimo/install/modelsim_libs/register_interface_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap pulp_soc_lib /home/kly/pulpissimo/install/modelsim_libs/pulp_soc_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap tbtools_lib /home/kly/pulpissimo/install/modelsim_libs/tbtools_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap tb_lib /home/kly/pulpissimo/install/modelsim_libs/tb_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap vip_lib /home/kly/pulpissimo/install/modelsim_libs/vip_lib 
Modifying modelsim.ini
QuestaSim-64 vmap 10.7c Lib Mapping Utility 2018.08 Aug 17 2018
vmap pulpissimo_lib /home/kly/pulpissimo/install/modelsim_libs/pulpissimo_lib 
Modifying modelsim.ini
make -C ../rtl/tb/remote_bitbang all
make[2]: Entering directory '/home/kly/pulpissimo/rtl/tb/remote_bitbang'
cc -MT remote_bitbang.o -MMD -MP -MF ./.d/remote_bitbang.Td -std=gnu11 -fno-strict-aliasing -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-function -Wno-missing-braces -O2 -g -march=native -DENABLE_LOGGING -DNDEBUG -fPIC -I./  \
	-c  remote_bitbang.c -o remote_bitbang.o 
cc -MT sim_jtag.o -MMD -MP -MF ./.d/sim_jtag.Td -std=gnu11 -fno-strict-aliasing -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-function -Wno-missing-braces -O2 -g -march=native -DENABLE_LOGGING -DNDEBUG -fPIC -I./  \
	-c  sim_jtag.c -o sim_jtag.o 
ld -shared -E --exclude-libs ALL -o librbs.so  \
	remote_bitbang.o sim_jtag.o 
make[2]: Leaving directory '/home/kly/pulpissimo/rtl/tb/remote_bitbang'
  Building common_cells/common_cells_all
  Building L2_tcdm_hybrid_interco/soc_interconnect
  Building cluster_interconnect/low_latency_interco
  Building cluster_interconnect/peripheral_interco
  Building cluster_interconnect/tcdm_interconnect
  Building adv_dbg_if/adv_dbg_if
  Building apb2per/apb2per
  Building apb_adv_timer/apb_adv_timer
  Building apb_fll_if/apb_fll_if
  Building apb_gpio/apb_gpio
  Building apb_node/apb_node
  Building apb_interrupt_cntrl/apb_interrupt_cntrl
  Building axi/axi
  Building axi_slice/axi_slice
  Building timer_unit/timer_unit
  Building fpu_div_sqrt_mvp/div_sqrt_top_mvp
  Building fpnew/fpnew
  Building jtag_pulp/jtag_pulp
  Building cv32e40p/riscv_regfile_rtl
  Building cv32e40p/riscv
  Building cv32e40p/riscv_vip_rtl
  Building cv32e40p/tb_riscv
  Building ibex/ibex
  Building ibex/ibex_vip_rtl
  Building ibex/ibex_regfile_rtl
  Building scm/scm
  Building generic_FLL/fll
  Building tech_cells_generic/tech_cells_rtl
  Building tech_cells_generic/tech_cells_rtl_synth
  Building udma_core/udma_core
  Building udma_uart/udma_uart
  Building udma_i2c/udma_i2c
  Building udma_i2s/udma_i2s
  Building udma_qspi/udma_qspi
  Building udma_sdio/udma_sdio
  Building udma_camera/udma_camera
  Building udma_filter/udma_filter
  Building udma_external_per/udma_external_per
  Building udma_hyper/udma_hyper
  Building hwpe_ctrl/hwpe-ctrl
  Building hwpe_ctrl/tb_hwpe_ctrl
  Building hwpe_stream/hwpe-stream
  Building hwpe_stream/tb_hwpe_stream
  Building hwpe_mac_engine/hw-mac-engine
  Building riscv_dbg/riscv-dbg
  Building register_interface/register_interface
  Building register_interface/reggen_primitives
  Building register_interface/register_interface_test
  Building pulp_soc/pulp_soc
  Building pulp_soc/udma_subsystem
  Building pulp_soc/fc
  Building pulp_soc/components
  Building pulp_soc/components_rtl
  Building pulp_soc/components_behav
  Building tbtools/tbtools
  Building tb/tb
  Building vip/open_models
  Building pulpissimo/pulpissimo
/home/kly/pulpissimo/sim//tcl_files/rtl_vopt.tcl
/usr/bin/env: ‘tclsh’: No such file or directory
make[1]: *** [Makefile:43: opt] Error 127
make[1]: Leaving directory '/home/kly/pulpissimo/sim'
make: *** [Makefile:114: build] Error 2

**Comment by bluewww** [comment]
The error message says you don't have the `tcl` shell installed on your machine. You can search the internet on how to do this on your particular distribution.

**Comment by kangliyu1** [comment]
> Yes, you can ignore them. They mostly relate to the fact that the proprietary (but optional) verification IPs are not installed on your machine.

Thank you very much for your reply
