### ISSUE TITLE
saxpy with FPU no floating instruction.

### ISSUE THREAD

**Issue by lfernand4** [pulp-platform/pulpissimo#28]
I want to compare the benefit of the FPU. But for the moment I see that the RISCY+FPU is slower.
I use the following function : 
![image](https://user-images.githubusercontent.com/36438648/43004862-4f1d481c-8c31-11e8-987c-a24174fc0cd3.png)

x and y are float and the coef is 1.2. 

The result : 
![image](https://user-images.githubusercontent.com/36438648/43004921-776ba386-8c31-11e8-839f-945572e0ff4c.png)

I use this command to disassemble: make dis disopt="-d -l" | less

And I see that RISCY+FPU don't use floating instruction : 

![image](https://user-images.githubusercontent.com/36438648/43005392-0142953c-8c33-11e8-94c5-4bb7f2ff8d84.png)

Do you know why ?

Thanks in advance.

**Comment by haugoug** [comment]
It seems you are using double not float, and double are SW emulated. Make sure all constants are described like 1.5f. 
Also did you use this config: configs/pulpissimo.sh
Could you show one of the gcc command which was executed to compile your code.

**Comment by lfernand4** [comment]
thanks  ! it work with PULPISSIMO. 
But with PULP it doesn't work in float if I define ceof in float (1.2f).
