### ISSUE TITLE
Why the new tool Chain?

### ISSUE THREAD

**Issue by 2ndDula** [pulp-platform/pulpissimo#29]
Hi, 
I would like to ask, why you have created the new "pulp-riscv-gnu-toolchain" for pulpissimo instead of continue using the "ri5cy_gnu_toolchain" that supports pulpino? 
Many Thanks

**Comment by haugoug** [comment]
Hi,
ri5cy_gnu_toolchain was a fork of an old version of the generic riscv toolchain plus a lot of modifications for pulp which made it difficult to bring recent developments in the generic riscv toolchain.
To get recent developments, we then preferred to fork again the generic toolchain in pulp-riscv-gnu-toolchain and bring our extensions.

**Comment by 2ndDula** [comment]
Thanks
