### ISSUE TITLE
Error while building the RTL simulation platform

### ISSUE THREAD

**Issue by MahmouodMagdi** [pulp-platform/pulpissimo#293]
I am trying to build the RTL simulation platfrom 

1. git clone https://github.com/pulp-platform/pulp
2. cd pulp
3. source setup/vsim.sh
4. make checkout 

and i get this error 

error: Failed to initialize git database

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Makefile:41: recipe for target 'checkout' failed
make: *** [checkout] Error 1

anyone can help  me, pls?

**Comment by bluewww** [comment]
This is related to github and not pulpissimo. You need to add your public key to your github account.

**Comment by MahmouodMagdi** [comment]
Thanks for your help
