### ISSUE TITLE
Process HWPE events in PULPissimo with pulp-runtime

### ISSUE THREAD

**Issue by rijun** [pulp-platform/pulpissimo#300]
Hello,

I have successfully integrated a HWPE into PULPissimo, and am able to control it via the APB interface. To signal that the HWPE has finished its computation, a signal is emitted which is connected to the `evt_o` output of the fc_hwpe module in pulp_soc. I can see this signal also in the soc_event_generator, under `per_events_i[140]`.

However, I have trouble receiving this signal in my C code. I'm using the pulp-runtime and my codes looks something like this:

```C
#include <stdio.h>
#include <pulp.h>
#include "archi/chips/pulp/memory_map.h"
#include "archi/eu/eu_v3.h"
#include "hal/eu/eu_v3.h"

#define HWPE_EVENT_MASK (32*4+12)   // = ARCHI_SOC_EVENT_FCHWPE0 (140)

int main()
{
    printf("Hello!\n");
    printf("Writing data\n");
    // Code omitted
    printf("Writing data finished, waiting for result\n");   
    eu_fc_evt_maskWaitAndClr(HWPE_EVENT_MASK);
    printf("Computation finished\n");
    return 0;
}
```

The issue I'm having is that the processor does not wait until the event is set, it continues directly after finishing the data writing part. I  can observe in Questa that the event signal is only set a lot later. I also found this function in the HAL, `soc_eu_fcEventMask_setEvent(ARCHI_SOC_EVENT_FCHWPE0);`, but I am unsure which one to use. Or should I use a SoC event interrupt like mentioned in [https://pulp-platform.org/community/showthread.php?tid=240](https://pulp-platform.org/community/showthread.php?tid=240)?

Regards,
rijun

**Comment by meggiman** [comment]
If I'm not mistaken the `eu_fc_evt_maskWaitAndClr` function internally uses a sychronization primitive only available in the pulp_cluster which is not present in the single-core PULPissimo. Instead you can indeed use the snippet I provided in the forum to create your own barrier e.g. by setting a boolean flag in your registered ISR when you received the HWPE interrupt and calling hal_itc_wait_for_interrupt() followed by a check if the boolean flag is set in a loop in your main thread (in case you want to block the main thread). If you need to support more complex synchronization and multi-tasking schemes you might be interested to have a look at [pulp-freertos port](https://github.com/pulp-platform/pulp-freertos).  @bluewww is the SoC event unit already supported with a FreeRTOS compatible API?

**Comment by rijun** [comment]
Ok, thanks for the reply. I implemented the following code, as described in the forum:

```C
#include <stdio.h>
#include <pulp.h>
#include "archi/chips/pulp/memory_map.h"
#include "archi/eu/eu_v3.h"
#include "hal/eu/eu_v3.h"

volatile int hwpeFlag = 0;

void handle_hwpe_event_interrupts(void ) __attribute((interrupt));
void handle_hwpe_event_interrupts(void) {
    hwpeFlag = 1;
}

int main()
{
    printf("Hello!\n");
    
    // Set interrupt handle for HWPE events (IRQ 30)
    rt_irq_set_handler(30, handle_hwpe_event_interrupts);
    // Enable hwpe_event interrupts (IRQ 30)
    hal_itc_enable_set(1<<30);
    
    /* Writing omitted */

    while (1) {
        printf("Waiting for result...\n");
        hal_itc_wait_for_interrupt();
        if (hwpeFlag == 1) {
            break;
        }
    }

    /* Reading omitted */
}
```

Initially nothing changed, the interrupt was triggered but not propagated to the SoC. I had to change the `FC_EVENT_POS` parameter in the event generator module instantiation from `7` to `140`, afterwards everything worked as expected. Is this parameter a bug?

**Comment by cortalo** [comment]
Hi @rijun,

I have the same question. Did you find it out? Is it a valid solution to change `FC_EVENT_POS` from 7 to 140?

Best,
Long

**Comment by rijun** [comment]
Hi @cortalo,

yes, after changing `FC_EVENT_POS` the event was triggered just as expected.
