### ISSUE TITLE
error for make checkout

### ISSUE THREAD

**Issue by nicolast0604** [pulp-platform/pulpissimo#302]
The authenticity of host 'github.com (52.69.186.44)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no)? yes
error: Failed to initialize git database in "/home/nicolast0604/pulpissimo/.bender/git/db/tech_cells_generic-8815a230545f74d7". Git command ("git" "fetch" "--prune" "origin") in directory "/home/nicolast0604/pulpissimo/.bender/git/db/tech_cells_generic-8815a230545f74d7" failed with exit code 128:

Warning: Permanently added 'github.com,52.69.186.44' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Makefile:54: recipe for target 'checkout' failed
make: *** [checkout] Error 1

**Comment by meggiman** [comment]
duplicate  of #303
