### ISSUE TITLE
error for make scripts

### ISSUE THREAD

**Issue by nicolast0604** [pulp-platform/pulpissimo#303]
error: Failed to initialize git database in "/home/nicolast0604/pulpissimo/.bender/git/db/common_cells-08ba5450e7bdaa5d". Git command ("git" "fetch" "--prune" "origin") in directory "/home/nicolast0604/pulpissimo/.bender/git/db/common_cells-08ba5450e7bdaa5d" failed with exit code 128:

Warning: Permanently added the ECDSA host key for IP address '52.192.72.89' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Makefile:58: recipe for target 'Bender.lock' failed
make: *** [Bender.lock] Error 1

**Comment by meggiman** [comment]
Please add your public ssh key to your Github account, make sure your private key is loaded (ssh-agent) and try again.
