### ISSUE TITLE
Synopsys DC Timing Loops detected

### ISSUE THREAD

**Issue by Ahmedsaied9** [pulp-platform/pulpissimo#318]
I am using Synopsys DC of Version G-2012.06-SP2 and using latest version of the ips.

When I executed `check_timing -include loop` in dc_shell, it outputed the following timing (combinational) loops:

`Information: Checking loops...
Warning: timing loops detected. (TIM-209)
    #              loop breakpoint

                 cell_arc                            lib cell
--------------------------------------------------------------------------------
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/clk_en_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/clk_en_reg/Q saed32rvt_ss0p7vn40c/LATCHX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/U3/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U57632/A                 -> U57632/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
U49890/A                 -> U49890/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/r_clockout_mux_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/r_clockout_mux_reg/Q saed32rvt_ss0p7vn40c/SDFFASX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/clk_mux_i/U2/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/clk_mux_i/U2/Y saed32rvt_ss0p7vn40c/AO22X1_RVT #
U80109/A                 -> U80109/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/clk_en_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/clk_en_reg/Q saed32rvt_ss0p7vn40c/LATCHX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/U3/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U57372/A                 -> U57372/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/clk_en_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/clk_en_reg/Q saed32rvt_ss0p7vn40c/LATCHX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/U3/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U16663/A4                -> U16663/Y                 saed32rvt_ss0p7vn40c/AO22X1_RVT  
pad_frame_i/padinst_sdio_clk/__tmp100/A -> pad_frame_i/padinst_sdio_clk/__tmp100/Y saed32rvt_ss0p7vn40c/TNBUFFX8_RVT  
U21049/A                 -> U21049/Y                 saed32rvt_ss0p7vn40c/NBUFFX16_RVT  
soc_domain_i/pulp_soc_i/i_clk_rst_gen/clk_mux_fll_per_i/U2/A3 -> soc_domain_i/pulp_soc_i/i_clk_rst_gen/clk_mux_fll_per_i/U2/Y saed32rvt_ss0p7vn40c/AO22X1_RVT  
U80106/A                 -> U80106/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  

                 cell_arc                            lib cell
--------------------------------------------------------------------------------
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/U3/A2 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_udmacore/genblk1[4].i_clk_gate_per/i_clk_gate/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U57632/A                 -> U57632/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
U49890/A                 -> U49890/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/r_clockout_mux_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/r_clockout_mux_reg/Q saed32rvt_ss0p7vn40c/SDFFASX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/clk_mux_i/U2/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/clk_mux_i/U2/Y saed32rvt_ss0p7vn40c/AO22X1_RVT #
U80109/A                 -> U80109/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/clk_en_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/clk_en_reg/Q saed32rvt_ss0p7vn40c/LATCHX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/U3/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/u_clockgen/i_clk_gate/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U57372/A                 -> U57372/Y                 saed32rvt_ss0p7vn40c/INVX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/clk_en_reg/CLK -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/clk_en_reg/Q saed32rvt_ss0p7vn40c/LATCHX1_RVT  
soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/U3/A1 -> soc_domain_i/pulp_soc_i/soc_peripherals_i/i_udma/i_sdio/i_sdio_txrx/i_clk_gate_sdio/U3/Y saed32rvt_ss0p7vn40c/AND2X1_RVT #
U16663/A4                -> U16663/Y                 saed32rvt_ss0p7vn40c/AO22X1_RVT  
pad_frame_i/padinst_sdio_clk/__tmp100/A -> pad_frame_i/padinst_sdio_clk/__tmp100/Y saed32rvt_ss0p7vn40c/TNBUFFX8_RVT  
U21049/A                 -> U21049/Y                 saed32rvt_ss0p7vn40c/NBUFFX16_RVT  
soc_domain_i/pulp_soc_i/i_clk_rst_gen/clk_mux_fll_per_i/U2/A3 -> soc_domain_i/pulp_soc_i/i_clk_rst_gen/clk_mux_fll_per_i/U2/Y saed32rvt_ss0p7vn40c/AO22X1_RVT  
` 

[Timing Loops.txt](https://github.com/pulp-platform/pulpissimo/files/8354737/Timing.Loops.txt)

- How could I solve them?

**Comment by gautschimi** [comment]
you should use proper clock gating cells. I think you are using the simulation models that consist of a latch and an and gate. that will not work for synthesis
