### ISSUE TITLE
Error Zedboard Example with IBEX Core - Placement Error 

### ISSUE THREAD

**Issue by mbaykenar** [pulp-platform/pulpissimo#322]
Last time I issued about zedboard example with IBEX core selected. Bender is updated with PR:
https://github.com/pulp-platform/pulpissimo/pull/319

I recloned and retry the zedboard example with IBEX core selected. This time Vivado gave an error in placement phase:
----------------------------------------------------------------------------------------------------------------------------------
ERROR: [Place 30-574] Poor placement for routing between an IO pin and BUFG. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
    < set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pad_reset_IBUF] >

    pad_reset_IBUF_inst (IBUF.O) is locked to IOB_X1Y52
    pad_reset_IBUF_BUFG_inst (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y18
Resolution: Poor placement of an IO pin and a BUFG has resulted in the router using a non-dedicated path between the two.  There are several things that could trigger this DRC, each of which can cause unpredictable clock insertion delays that result in poor timing.  This DRC could be caused by any of the following: (a) a clock port was placed on a pin that is not a CCIO-pin (b)the BUFG has not been placed in the same half of the device or SLR as the CCIO-pin (c) a single ended clock has been placed on the N-Side of a differential pair CCIO-pin.
Phase 1.2 IO Placement/ Clock Placement/ Build Placer Device | Checksum: b7106ea0

Time (s): cpu = 00:00:18 ; elapsed = 00:00:10 . Memory (MB): peak = 2470.672 ; gain = 0.000 ; free physical = 15570 ; free virtual = 28678
Phase 1 Placer Initialization | Checksum: b7106ea0

Time (s): cpu = 00:00:18 ; elapsed = 00:00:10 . Memory (MB): peak = 2470.672 ; gain = 0.000 ; free physical = 15570 ; free virtual = 28678
ERROR: [Place 30-99] Placer failed with error: 'IO Clock Placer failed'
Please review all ERROR, CRITICAL WARNING, and WARNING messages during placement to understand the cause for failure.
Ending Placer Task | Checksum: b7106ea0
----------------------------------------------------------------------------------------------------------------------------------
The message says with adding CLOCK_DEDICATED_ROUTE FALSE constraint on pad_reset_IBUF net will convert the error to warning. However, are we sure that this message filtering is no harm to implementation?

Regards,
Burak

**Comment by meggiman** [comment]
Hi @mbaykenar 

These kind of errors show up if you run out of dedicated clock routes on your FPGA. Adding the `clock_dedicated_route false` constraint on the pad should indeed resolve the issue. However, the trade of is that the timing of this path will become very poor.   If you don't really care about max frequency and just want something that works, go ahead. We used this hack a couple of times in the past and the FPGA port of PULPissimo was still working decently. However, if your timing is deteriorating to unacceptable levels I am afraid you will have to either buy a larger FPGA or optimize the RTL yourself. Note that PULPissimo is not optimized for FPGA but targets ASIC implementations. We just happen to provide an FPGA port that allows emulation but it is not optimized for performance at all.

Best,
Manuel

**Comment by mbaykenar** [comment]
Hi @meggiman  

Thanks for the clarification. 

Regards,
Burak
