### ISSUE TITLE
PULP toolchain demands ETH password

### ISSUE THREAD

**Issue by LatifAkcayGithub** [pulp-platform/pulpissimo#325]
Hello,

While trying to clone pulp-gcc-toolchain from https://github.com/pulp-platform/riscv-gnu-toolchain, the eth openSSH password is required. I think this is because of a confusion during the source updates. Please check it. 

Regards

**Comment by bluewww** [comment]
Can you post the exact error message please? There are no git remotes pointing to ETH internal addresses.

**Comment by LatifAkcayGithub** [comment]
Hello, 
please see the attached screenshot for the issue.
Thanks

![errorETH](https://user-images.githubusercontent.com/17648687/162761894-abd87a75-3a81-4325-a1b8-fc5ef5532981.png)

**Comment by bluewww** [comment]
Ah I see you copied the link from the README.md instead of cloning the repository normally. I will update the README.md

**Comment by bluewww** [comment]
Fixed in https://github.com/pulp-platform/riscv-gnu-toolchain/commit/ba8d2d854895f52208d4efef7044d1c0395419d8
