### ISSUE TITLE
make checkout failed

### ISSUE THREAD

**Issue by neekoli** [pulp-platform/pulpissimo#333]
The image below shows the v7 pulpissimo after "make checkout", with "ips" "iptools" added. 
![image](https://user-images.githubusercontent.com/85484936/165308719-efb3e35c-e0ae-4a04-a7d0-91c552a8218e.png)
However, when I download the latest version of "make checkout", I tried  "make checkout" to get other ips. But 2 problems occurred as follows.

- axi version conflict
- no ips were cloned successfully

![image](https://user-images.githubusercontent.com/85484936/165308168-af1460c0-6c14-4165-ae53-e4b5806645c3.png)
![dc16163a33eca641741e13cf873ca36](https://user-images.githubusercontent.com/85484936/165308243-71804c46-7557-4ef2-a629-d15d3581818e.png)
(The image below shows the latest verison pulpissimo after "make checkout", with no "ips" "iptools" added. )
![image](https://user-images.githubusercontent.com/85484936/165308624-a5c27da3-ffb5-4eb1-92b8-5cf703a7e386.png)

**Comment by bluewww** [comment]
The upgrade path from older version is unfortunately not well supported due to the tooling changes we did lately (deprecating and removing ipstools).

When I run `make checkout` on a freshly cloned pulpissimo I don't get any errors.

**Comment by neekoli** [comment]
> The upgrade path from older version is unfortunately not well supported due to the tooling changes we did lately (deprecating and removing ipstools).
> 
> When I run `make checkout` on a freshly cloned pulpissimo I don't get any errors.

Thank you. But I did run "make checkout" on a freshly cloned pulpissimo today in Ubuntu 18.04.

**Comment by micprog** [comment]
For the `axi` version issue, you can also just select one of the `axi` versions. I know the `v0.29.1` version is tested, but there shouldn't be any major conflicts with the newer versions. The `axi` dependency will be updated in upcoming versions to avoid manual selection when re-resolving dependency versions. I'm unsure why bender is re-resolving dependencies on your system when running `make checkout`, if the `Bender.lock` file is available this should not happen.

For the IPs, with the new dependency management, no `ips` or `ipstools` folder will be created, as dependencies are now managed with bender. Please check the readme https://github.com/pulp-platform/pulpissimo#where-are-all-the-sub-ips-dependencies for more details.

**Comment by neekoli** [comment]
> For the `axi` version issue, you can also just select one of the `axi` versions. I know the `v0.29.1` version is tested, but there shouldn't be any major conflicts with the newer versions. The `axi` dependency will be updated in upcoming versions to avoid manual selection when re-resolving dependency versions. I'm unsure why bender is re-resolving dependencies on your system when running `make checkout`, if the `Bender.lock` file is available this should not happen.
> 
> For the IPs, with the new dependency management, no `ips` or `ipstools` folder will be created, as dependencies are now managed with bender. Please check the readme https://github.com/pulp-platform/pulpissimo#where-are-all-the-sub-ips-dependencies for more details.

Oh I see！I truly appreciate your timely help~
