### ISSUE TITLE
Bootloader documentation

### ISSUE THREAD

**Issue by iDoka** [pulp-platform/pulpissimo#338]
As described [here](https://github.com/pulp-platform/pulpissimo/blob/master/boot/README.md) PULPissimo have several capabilities for running boot process.
JTAG boot and QSPI boot are quite straight-forward way to booting.

The blind spot for me - Interaction over UART to booting over zforth shell. What is protocol used for `zforth` shell interaction? 

I have no doubts that `zforth` part already described somewhere but I still not yet find it.

**Comment by bluewww** [comment]
[Zforth](https://github.com/zevv/zForth) is a small implementation of a forth like programming language. You talk to it by sending commands (ascii characters terminated by a newline) over uart.

**Comment by bluewww** [comment]
1. These are defines in the C-code. See `boot/boot_code.c`.
2. the srec format has a entry point node. Once this is read the core will automatically jump to that address and start executing.

**Comment by iDoka** [comment]
Last question (just for my engineering curiosity): what is the use cases for zforth?

**Comment by bluewww** [comment]
Debugging and chip bringup. You can just not compile it in to the bootrom if you don't need it.
