### ISSUE TITLE
Pulp for python plugin problem with distribution

### ISSUE THREAD

**Issue by Imantsg** [pulp-platform/pulpissimo#344]
When I upload my package and create distribution it returns unusable base_url

"base_url": "https://d18954d39a00/pypi/tartarus/master/"

I use pulp docker image and my settings.py file is like this
CONTENT_ORIGIN='https://pulp.ozoli.lv'
ANSIBLE_API_HOSTNAME='https://pulp.ozoli.lv'
ANSIBLE_CONTENT_HOSTNAME='https://pulp.ozoli.lv/pulp/content'
TOKEN_AUTH_DISABLED=True

it should return https://pulp.ozoli.lv/pypi/tartarus/master/

**Comment by meggiman** [comment]
I am pretty sure this is the wrong repository to report your issue. Pulpissimo is a microcontroller i.e. a hardware project and has nothing to do with anything python related.
