### ISSUE TITLE
Minimal example for accelerator

### ISSUE THREAD

**Issue by christian-lanius** [pulp-platform/pulpissimo#346]
Hello!
I am attempting to integrate pulpissimo with different accelerators, which have an AXI memory mapped interface for configuration and an AXI stream interface for the data to be processed. The AXI stream interface I would want to drive from udma.
If I understand correctly, the HWPE MAC example is very similar to this, however I am somewhat lost about how I would go about integrating this into pulpissimo. 
Longer term, I would like to create external ports for AXI and AXI stream so that I can synthesize/implement the different parts of the design hierarchically.

Specifically, are there some pointers regarding:
- Is there a way for me to create a new R/W udma channel and connect it all the way to the top level and is this an okay solution to get an AXI stream?
- Can I use the async_data_master* signals to drive my control register file in the slave?
- What do I have to do to extend the memory map to contain my accelerator? To interact with the accelerator, is it as simple as having it in my memory range and then writing/reading to it?
- What is the recommended to write minimal software to control the AXI stream, is keeping to pulp-runtime/drivers/uart.c as an example a good idea?

I hope the questions are clear and I would be very glad to get some advice.

Kind regards
Christian

**Comment by bluewww** [comment]
Did you managed to get answers to your questions?
