### ISSUE TITLE
Physical Memory Protection (PMP) in pulpissimo

### ISSUE THREAD

**Issue by sammy17** [pulp-platform/pulpissimo#361]
Does pulpissimo configure physical memory protection (PMP) in the boot code? 

I noticed that CV32 does not support PMP but ibex does. So the above question is only valid for pulpissimo with ibex core. 

Also, does pulpissimo implement PMP checks for memory accesses by peripherals? 
For example, when HWPE accelerator access a memory address, does that access go through PMP checks? 

I am looking into the memory security of RISC-V SoCs and any help in understanding pulpissimo better is appreciated.

**Comment by bluewww** [comment]
PULPissimo currently doesn't do any PMP checks at all though implementing the PMP for cv32 (rather enabling it and verifying it) is on the TODO list.
