### ISSUE TITLE
Zedboard running script is missing

### ISSUE THREAD

**Issue by gyx3598** [pulp-platform/pulpissimo#380]
Zedboard running script is missing
![2023-01-04 16-18-34屏幕截图](https://user-images.githubusercontent.com/63686359/210512649-b35a964a-0975-40c3-9cd1-ba7b7e7a15da.png)

**Comment by micprog** [comment]
Please make sure to run `make scripts` in the project root, as described in the [Readme](https://github.com/pulp-platform/pulpissimo#bitstream-generation). This will create the generated script which properly includes the needed source files.
