### ISSUE TITLE
I can't get tests. The git clone needs a password. What should I do?

### ISSUE THREAD

**Issue by gyx3598** [pulp-platform/pulpissimo#383]
I can't get tests. The git clone needs a password. What should I do?

![image](https://user-images.githubusercontent.com/63686359/217772928-58c55680-9563-4c4a-8248-2a0f371e3ad0.png)

**Comment by micprog** [comment]
Hi @gyx3598,
Unfortunately we do not share all our internal tests, and some of the commands in the makefile are for internal purposes. I suggest you have a look at https://github.com/pulp-platform/regression_tests/tree/master/ml_tests, as far as I know all the tests you are looking for can be found there as well. Other examples can be found [here](https://github.com/pulp-platform/pulpissimo#downloading-and-running-examples), and more guides are also [here](https://github.com/pulp-platform/pulpissimo#simple-runtime).

Also, please do not spam all open issues. We provide the code open-source, however support is something we generally do not provide freely, only if we are available. Therefore, spamming all open issues with your problem, which is not related to the other issues, will cause us to block you from interacting with the group on github.

**Comment by gyx3598** [comment]
> 嗨@gyx3598，不幸的是，我们没有共享所有的内部测试，并且makefile中的某些命令用于内部目的。我建议你看看 https://github.com/pulp-platform/regression_tests/tree/master/ml_tests，据我所知，你正在寻找的所有测试也可以在那里找到。其他示例可以在这里找到，更多指南也[在这里](https://github.com/pulp-platform/pulpissimo#simple-runtime)。
> 
> 另外，请不要向所有未解决的问题发送垃圾邮件。我们提供开源代码，但是支持是我们通常不会免费提供的，只有在我们可用的情况下。因此，向所有与您的问题无关的未解决的问题发送垃圾邮件，这将导致我们阻止您与 github 上的群组互动。

Okay, I understand. Thank you
