### ISSUE TITLE
There was an error in the compilation of pulp-runtime examples. Is this the problem with the gcc compiler? Or is there a problem with my Centos7 environment?

### ISSUE THREAD

**Issue by gyx3598** [pulp-platform/pulpissimo#384]
There was an error in the compilation of pulp-runtime examples. Is this the problem with the gcc compiler? Or is there a problem with my Centos7 environment?

![2023-02-20 11-26-29屏幕截图](https://user-images.githubusercontent.com/63686359/220003180-65847a46-3cc8-4661-ae96-01d9eee20205.png)

**Comment by bluewww** [comment]
Please post the compiler version and give a link to the program you are trying to compile.

**Comment by gyx3598** [comment]
> 请发布编译器版本并提供指向您尝试编译的程序的链接。

The compiler uses riscv-gnu-toolchain release 2.5.0, and the code is release v7.0.0

**Comment by gyx3598** [comment]
> > 请发布编译器版本并提供指向您尝试编译的程序的链接。
> 
> The compiler uses riscv-gnu-toolchain release 2.5.0, and the code is release v7.0.0

![2023-02-21 16-38-28屏幕截图](https://user-images.githubusercontent.com/63686359/220292131-9c68f22d-9ae1-40c1-bc58-bb1591c570c1.png)

**Comment by bluewww** [comment]
Please use the lastest commit from the master branch for pulpissimo. Also I was asking about the *software* you are trying to compile.

**Comment by meggiman** [comment]
What software? Please answer the questions asked if you want help. It is impossible for us to know why compilation fails if we don't even know what you are trying to compile. We have no clue what repository and what piece of C-code you are referring to when you mention the "main branch code".

**Comment by gyx3598** [comment]
Sorry, I didn't make it clear. Under the main branch, enter the sim directory and execute “make build” and “make simc” respectively. You will find that the PC pointer is dead at 0x00000000: address. As shown below:

![image](https://user-images.githubusercontent.com/63686359/221410165-83bc4e8b-13f4-4d7a-91f0-a077ed6d4263.png)
