### ISSUE TITLE
error while simulating hello world 

### ISSUE THREAD

**Issue by AshwiniPohekar** [pulp-platform/pulpissimo#40]
Hello,

I am trying to simulate the Hello example for the pulpissimo platform. I have properly compiled the SDK for this platform. 
I am able to execute the make clean and make all commands. However, when I perform the make run option I get the following error:

```
Launching VSIM with command:
export VSIM_RUNNER_FLAGS="-gLOAD_L2=JTAG -permit_unmatched_virtual_intf -gBAUDRATE=625000" && vsim -64 -c -do 'source /home/ashwini/pulp-builder/pulpissimo-master/sim/tcl_files/config/run_and_exit.tcl' -do 'source /home/ashwini/pulp-builder/pulpissimo-master/sim/tcl_files/run.tcl; run_and_exit;'
Failed to open executable /home/ashwini/intelFPGA/18.1/modelsim_ase/linuxaloem/../linux_x86_64pe/vish in execute mode needed for the option -64.
execv: No such file or directory
** Fatal: Unable to exec the GUI /home/ashwini/intelFPGA/18.1/modelsim_ase/linuxaloem/../linux_x86_64pe/vish.
VSIM reported an error, leaving
/home/ashwini/pulp-builder/pulp-rt-examples-master/hello/build/pulpissimo/__rules.mk:143: recipe for target 'run' failed
make: *** [run] Error 1
```

I did dome debugging and figured out that because vsim is being launched with -64 option I am getting this particular error.

So, I figured out two solutions:
1. Find out why the -64 option is not running. This is a Intel-modelsim issue and I am not exactly sure whether changing anything here will even work.
2. Find out where vsim -64 is being called so that I can remove the -64 option and atleast try to run the hello world program without that. Is this option any good?

I am also attaching an image of the error log from the terminal with this port
![error](https://user-images.githubusercontent.com/8349323/52060218-0c072000-256c-11e9-8ed4-8a620d15d3c8.png)

**Comment by FrancescoConti** [comment]
Hi, this is clearly a tool-related issue. I am not sure this version of ModelSim, which is customized for Intel FPGAs, works at all with PULPissimo. Also, double-check that your machine is running 64bit Ubuntu.

Anyways, to workaround the issue you might try to drop the "-64" flag. In my case, this is doable by hacking the RTL runner in the SDK, which is found in `pkg/sdk/VERSION_NUMBER/install/ws/python/runner/rtl/vsim_runner.py`, around line 311. Good luck! :)

**Comment by AshwiniPohekar** [comment]
Hi,
> Hi, this is clearly a tool-related issue. I am not sure this version of ModelSim, which is customized for 
> Intel FPGAs, works at all with PULPissimo. Also, double-check that your machine is running 64bit
> Ubuntu.
Yes I am sure that my machine is running 64 bit Ubuntu. However, all the binaries provided for the Intel-ModelSim are 32 bit binaries. So I had to workaround that too !

> Anyways, to workaround the issue you might try to drop the "-64" flag. In my case, this is doable by
> hacking the RTL runner in the SDK, which is found in 
> pkg/sdk/VERSION_NUMBER/install/ws/python/runner/rtl/vsim_runner.py, around line 311

Yes this works for me. But now I have a different bug: 
# ** Error (suppressible): (vsim-19) Failed to access library 'models_lib' at "models_lib".
This is again a ModelSim error. After, some googling I have debugged that some changes have to be made to the Modelsim.ini file to get this to work. Still no success yet !

**Comment by FrancescoConti** [comment]
Have you built the RTL platform? https://github.com/pulp-platform/pulpissimo/blob/master/README.md#building-the-rtl-simulation-platform

**Comment by AshwiniPohekar** [comment]
Yes I have built the RTL platform. But I think the problem is that the Folder which contains the models is modelsim_libs where as somehow vsim is trying to access models_lib. 
I have also verified that the proper path is being assigned to access these models in the Modelsim.ini file.

**Comment by AshwiniPohekar** [comment]
Okay, then I was mistaken. Could you indicate where this library is located.

**Comment by haugoug** [comment]
By the way you can change the default vsim command with this env var:
export VSIM_COMMAND=vsim
By default it is set to vsim -64

**Comment by FrancescoConti** [comment]
@haugoug good insight! :)

@AshwiniPohekar it should be located under `pulpissimo/sim/modelsim_libs/`. You should find a  `modelsim.ini` symlink pointing to this directory inside the build directory of your test, e.g. `hello/build/pulpissimo/modelsim.ini`.

**Comment by AshwiniPohekar** [comment]
I checked but I could not find the models_lib folder under this path : pulpissimo/sim/modelsim_libs/
I had to bypass the vopt option while building the RTL since, there was no vopt in the Intel ModelSim version. 
Maybe, I have done the bypassing incorrectly !

**Comment by AshwiniPohekar** [comment]
But could vopt bypassing be the reason why models_lib is not getting generated.  Or there any other possibilities?

**Comment by AshwiniPohekar** [comment]
After using a licensed version of ModelSim I was able to compile the Hello World program and run it properly.

**Comment by dongwuzhao** [comment]
> 
> 
> After using a licensed version of ModelSim I was able to compile the Hello World program and run it properly.

Hi Ashwini, which licensed ModelSim did you used?  Is it the Intel/Altera ModelSim, or Mentor/Questa ModelSim?  I don't seem to find a vopt on the Intel ModelSim.

**Comment by AshwiniPohekar** [comment]
Hi dongwuzhao 

I used the Questa ModelSim. The exact version is 10.6e. Intel ModelSim student version does not come with vopt.

**Comment by salman0727** [comment]
i install and build rtl platform correctly but issues i will coming in make build option 
mkdir -p  /home/salman/riscv/pulpissimo/sim/modelsim_libs
/bin/bash: mkdir: command not found
make[2]: *** [vcompile/build.mk:67: /home/salman/riscv/pulpissimo/sim/modelsim_libs] Error 127
make[1]: *** [/home/salman/Desktop/riscv/pulpissimo/sim//vcompile/ips.mk:54: lib] Error 2
make: *** [Makefile:59: lib] Error 2
what can i do further ?? 
can anybody suggest me ?

thanking in advance
