### ISSUE TITLE
hwme/hwme.c:38: undefined reference to `hwme_vectstride2_set'

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#42]
I want try the MAC-accelerator;
The sdk is compiled following  the instructions: https://github.com/pulp-platform/pulp-sdk;
the toolchain is compiled following the instructions: https://github.com/pulp-platform/pulp-riscv-gnu-toolchain;

But I got the error as following:
pulp-sdk/pulp-rt-examples/accelerators/hwme/hwme.c:38: undefined reference to `hwme_vectstride2_set'
If it is commented in hwme.c, the hwme.c can be compiled successfully.

**Comment by FrancescoConti** [comment]
@haugoug I moved this to the PULPissimo tracker. Then I’ll deal with it myself ASAP

**Comment by bluewww** [comment]
This is a pulp-sdk bug which is probably not relevant anymore with the new pulp-sdk changes. Please open another issue if this is still a problem.
