### ISSUE TITLE
pulp_rt_examples/hello,  how to run it on GVSOC

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#43]
Hello, I want to try the pulp_rt_examples on GVSOC, which is the default platform described in Builder DOC.
But it always start the RTL simulation. Because I haven't install ModelSim, I got the error vsim command is not found.

If I want to run all pulp_rt_exmaples with GVSOC, which steps are needed to modified the Makefile?
I try to modify the configs/rtl.sh (platform=gvsoc) in pulp-builder, the following errors are got:
/*********************************************************************************************************
  File "/home/lgq/riscv2019/pulp-builder/install/ws/python/vp_core.py", line 479, in get_module
    file, path, descr = imp.find_module(x, path)
  File "/usr/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'pulp/itc/itc_v1'
/home/lgq/riscv2019/pulp-builder/pulp-rt-examples/hello/build/pulpissimo/__rules.mk:143: recipe for target 'run' failed
make: *** [run] Error 1
***********************************************************************************************************/

**Comment by FrancescoConti** [comment]
When you source the SDK, you should configure it for the correct target and simulation platform, e.g. (i go by memory as I am on mobile)
```
. pkg/sdk/config/pulpissimo.sh
. pkg/sdk/config/platform-gvsoc.sh
```

**Comment by tangshibin** [comment]
hello, 
what's the difference between pulp-builder and pulp-sdk?
The error about "hello-example and GVSOC" occurs in pulp-builder, and it is ok in pulp-sdk.
But I run pulp-rt-example/hwme on GVSOC, the error is got as following:
/*******************************************************************************
2546704416: 65883: [/sys/board/chip/soc/fc/warning                   ] Invalid access (offset: 0x1a10c004, size: 0x4, is_write: 0)
********************************************************************************/

**Comment by tangshibin** [comment]
pkg/sdk/config/platform-gvsoc.sh is not existed in pulp-builder/configs/

**Comment by haugoug** [comment]
pulp-builder is a simplified build process to more easily get the runtime for the RTL platform. To use gvsoc, you have to use pulp-sdk.

**Comment by Ahmed1Zaky** [comment]
> hello,
> what's the difference between pulp-builder and pulp-sdk?
> The error about "hello-example and GVSOC" occurs in pulp-builder, and it is ok in pulp-sdk.
> But I run pulp-rt-example/hwme on GVSOC, the error is got as following:
> /*******************************************************************************
> 2546704416: 65883: [/sys/board/chip/soc/fc/warning ] Invalid access (offset: 0x1a10c004, size: 0x4, is_write: 0)
> ********************************************************************************/

Have you found a solution for this error ? I am facing the same now.
