### ISSUE TITLE
how to use malloc function in the simulating platform?

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#45]
I'm writting a testing program with the malloc  function.
But I found the gvsoc report error in simulating the function, the error is  
![image](https://user-images.githubusercontent.com/18710552/53171118-d9a58b80-361c-11e9-9fcf-fabc3113e212.png)
![image](https://user-images.githubusercontent.com/18710552/53171170-f9d54a80-361c-11e9-9a1a-5bf4f08d2707.png)

It jump to the function start when calling the malloc function.

**Comment by haugoug** [comment]
There is no malloc available you have to use this function instead:
  void * ptr = rt_alloc(RT_ALLOC_FC_DATA, size);
