### ISSUE TITLE
how to use the vector-extension in pulpissimo?

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#47]
I want to try the vector-extension with FFT;
Do we provide any example for the use of the vector-extension?

**Comment by FrancescoConti** [comment]
A good and well organized source on how to use vectors is the SDK reference of GAP8, a commercial product based on PULP. E.g. here https://greenwaves-technologies.com/manuals/BUILD/PULP-OS/html/index.html#section37 and here https://greenwaves-technologies.com/manuals/BUILD/PULP-OS/html/group__groupPlp8Mac.html

Note that some of the vector extensions listed there are proprietary of GreenWaves Technologies, and not available in PULPissimo. These include complex arithmetics, which might be useful for FFTs. The ones I linked should however be all compatible with PULP.
