### ISSUE TITLE
How to report cycles with c-model

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#50]
hi, 
  I want to evaluate the execution time of a large program on GVSOC.
  I found that the instruction trace can report the cycles of the program, but it is too slow to simulate it with instruction trace.
  How can I evaluate the execution time faster?

**Comment by haugoug** [comment]
Hi,
gvsoc is simulating the performance counters that you can also use on a real chip so the easiest is that you use them on long programs. You can have a look at this example to see how it works: pulp-rt-examples/perf/fc/direct
