### ISSUE TITLE
Compiler Error for Makefile.sa

### ISSUE THREAD

**Issue by tangshibin** [pulp-platform/pulpissimo#51]
hi,
I would like to compile a sole simulator with the Makefile.sa in sdk/platform/gvsoc/models/cpu/iss；
But I got the compiler error for ‘iss_pccr_incr’;
How can I compile a sole simualtor with the peripheral devices;
The Makefile.sa works for which version of the gvsoc?

**Comment by haugoug** [comment]
Hi,
This special mode is no more supported, only the full system platform can be used.
