### ISSUE TITLE
Generate an instruction trace with GVSOC

### ISSUE THREAD

**Issue by k0nze** [pulp-platform/pulpissimo#52]
Hi,
how can I get an instruction trace when running a program on GVSOC?

**Comment by haugoug** [comment]
You can use this command:
 make run PLT_OPT=--trace=insn

**Comment by k0nze** [comment]
I was able to get an instruction trace with `export PULP_CURRENT_CONFIG_ARGS="gvsoc/trace=insn"` before executing `make run`
