### ISSUE TITLE
Generate VCD traces with GVSOC

### ISSUE THREAD

**Issue by donRaphaco** [pulp-platform/pulpissimo#58]
Hello,
I'm trying to get VCD traces of a program running on GVSOC, but I failed so far.
I tried with `make run CONFIG_OPT='gvsoc/vcd/active=True gvsoc/vcd/all=True gvsoc/vcd/gtkw=True'`, which creates `all.vcd` but gtkwave can't open it.

**Comment by haugoug** [comment]
Hello,
you should get a recent SDK, for example tag 2019.06.05, this feature has been improved. You can then use it like that:
make all run runner_args="--vcd"
And open the gtkwave script view.gtk
You can also dump much more events with (like PC and debug symbols):
make conf all runner_args="--vcd --event=.*" run
